// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/opera/opera.proto

package fuckopera_service_opera

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Opera service

func NewOperaEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Opera service

type OperaService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Opera_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Opera_PingPongService, error)
}

type operaService struct {
	c    client.Client
	name string
}

func NewOperaService(name string, c client.Client) OperaService {
	return &operaService{
		c:    c,
		name: name,
	}
}

func (c *operaService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Opera.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operaService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Opera_StreamService, error) {
	req := c.c.NewRequest(c.name, "Opera.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &operaServiceStream{stream}, nil
}

type Opera_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type operaServiceStream struct {
	stream client.Stream
}

func (x *operaServiceStream) Close() error {
	return x.stream.Close()
}

func (x *operaServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *operaServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *operaServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *operaServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *operaService) PingPong(ctx context.Context, opts ...client.CallOption) (Opera_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Opera.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &operaServicePingPong{stream}, nil
}

type Opera_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type operaServicePingPong struct {
	stream client.Stream
}

func (x *operaServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *operaServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *operaServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *operaServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *operaServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *operaServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Opera service

type OperaHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Opera_StreamStream) error
	PingPong(context.Context, Opera_PingPongStream) error
}

func RegisterOperaHandler(s server.Server, hdlr OperaHandler, opts ...server.HandlerOption) error {
	type opera interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Opera struct {
		opera
	}
	h := &operaHandler{hdlr}
	return s.Handle(s.NewHandler(&Opera{h}, opts...))
}

type operaHandler struct {
	OperaHandler
}

func (h *operaHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.OperaHandler.Call(ctx, in, out)
}

func (h *operaHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.OperaHandler.Stream(ctx, m, &operaStreamStream{stream})
}

type Opera_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type operaStreamStream struct {
	stream server.Stream
}

func (x *operaStreamStream) Close() error {
	return x.stream.Close()
}

func (x *operaStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *operaStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *operaStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *operaStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *operaHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.OperaHandler.PingPong(ctx, &operaPingPongStream{stream})
}

type Opera_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type operaPingPongStream struct {
	stream server.Stream
}

func (x *operaPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *operaPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *operaPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *operaPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *operaPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *operaPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
